# Generated by Django 3.0.3 on 2020-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecatalog',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='phonecatalog',
            name='reg_date',
            field=models.DateTimeField(),
        ),
    ]
